title: Sara Abraham # your name (or website title) here
logo: "/images/image.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Computer Science student looking for an internship. Eager to learn more through an internship.
  <br><br>
  <a href="https://www.linkedin.com/in/sara-abraham-5b1797278/">View My LinkedIn Profile</a> 
  

